services:
  nginx:
    container_name: nginx
    build:
      context: ./service/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        TZ: ${TZ}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params
      - ${NGINX_LOG_DIR}:/var/log/nginx
    restart: always
    depends_on:
      - php82
    networks:
      dnmp_network:
        ipv4_address: 172.19.0.10

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: [
      "redis-server", "/etc/redis.conf",
      "--requirepass", "${REDIS_PASSWORD}"
    ]
    environment:
      TZ: ${TZ}
    networks:
      dnmp_network:
        ipv4_address: 172.19.0.20

  nodejs:
    image: node:${NODE_VERSION}
    container_name: nodejs
    ports:
      # 注意：大范围端口映射会影响 Docker 启动速度
      - "${NODE_HOST_PORT}"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
    environment:
      NODE_ENV: ${NODE_ENV}
      TZ: ${TZ}
    entrypoint: ["sh", "-c", "npm install -g pnpm && tail -f /dev/null"]
    restart: always
    stdin_open: true
    tty: true
    networks:
      dnmp_network:
        ipv4_address: 172.19.0.30

  mysql8:
    image: mysql:${MYSQL8_VERSION}
    container_name: mysql8
    ports:
      - "${MYSQL8_HOST_PORT}:3306"
    volumes:
      - ${MYSQL8_CONF_FILE}:/etc/mysql8/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql8:/var/lib/mysql/:rw
      - ${MYSQL8_LOG_DIR}:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL8_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL8_ROOT_HOST}
      TZ: ${TZ}
    restart: always
    networks:
      dnmp_network:
        ipv4_address: 172.19.0.40

  mysql5:
    # 指定使用 amd64 平台, mac芯片m1-m4建议保留
    platform: linux/amd64
    container_name: mysql5
    image: mysql:${MYSQL5_VERSION}
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
      - ${MYSQL5_LOG_DIR}:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL5_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL5_ROOT_HOST}
      TZ: ${TZ}
    restart: always
    networks:
      dnmp_network:
        ipv4_address: 172.19.0.41

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./service/rabbitmq
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION}
        RABBITMQ_PLUGINS: ${RABBITMQ_PLUGINS}
    restart: always
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_S}:15672"
    volumes:
      - ${DATA_DIR}/rabbitmq:/var/lib/rabbitmq/:rw
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: ${TZ}
    networks:
      dnmp_network:
        ipv4_address: 172.19.0.50

  php82:
    container_name: php82
    build:
      context: ./service/php82
      args:
        PHP_VERSION: ${PHP82_VERSION}
        PHP_EXTENSIONS: ${PHP82_EXTENSIONS}
        DEBIAN_MIRROR_DOMAIN: deb.debian.org
        TZ: ${TZ}
    ports:
      # 注意：大范围端口映射会影响 Docker 启动速度
      - "${PHP82_HOST_PORT}"
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP82_PHP_CONF_FILE}:/usr/local/etc/php/php.ini
      - ${PHP82_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      - ${PHP82_LOG_DIR}:/var/log/php
      - ${PHP82_DATA_COMPOSER}:/tmp/composer
    restart: always
    privileged: true
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mysql8
      - redis
    networks:
      dnmp_network:
        ipv4_address: 172.19.0.60

networks:
  dnmp_network:
    driver: bridge
    ipam:
      driver: default
      config:
        # 使用 172.19.x.x 避免与常见的 192.168 或 10.0 冲突
        - subnet: 172.19.0.0/24